project:
  type: website
  output-dir: docs

  

website:
  title: "Russian elections'04-24"
  navbar:
    left:
      - href: index.qmd
        text: Текст
      - href: about.qmd
        text: Карта

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    fontsize: 1em
  
editor: visual

