project:
  type: website
  output-dir: docs

  
website:
  title: "Russian elections'04-24"
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    fontsize: 1.2em
    mainfont: NotoSerif, serif;
editor: visual

