project:
  type: website
  output-dir: docs
  

website:
  title: "Russian elections'04-24"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
  
editor: visual

